name = "scoring-parameters"

[defaults]
builder = "docker:generic"
runner = "local:docker"
disable_metrics = false

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "scoring-parameters"
instances = { min = 3, max = 100, default = 3 }
  [testcases.params]
  seed = { type = "int", desc = "Seed to use for the rng", default = 40 }
  no_val_percentage = { type = "int", desc = "% of nodes without vals", default = 0 }
  total_validators = { type = "int", desc = "number of validators", default = 200 }
  min_peers_per_node = { type = "int", desc = "minimum number of peers to connect to", default = 2 }
  max_peers_per_node_inclusive = { type = "int", desc = "maximum number of peers to connect to", default = 3 }
  run = { type = "int", desc = "Time to run the emulation", default=20, unit="sec" }
