{
 "title": "Gossipsub",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "run_id", "query": "ccrtv9r4lvk12ph2il8g" },
   { "name": "topic", "query": "emulate" },
   { "name": "instance_name", "query": "Publisher1" },
   {
    "name": "protocol",
    "query": "Gossipsubv1_1,Gossipsub,Floodsub,NotSupported"
   }
  ]
 },
 "panels": [
  { "title": "Metrics per known topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "topic_peers_counts (topic: ${topic})",
   "type": "barchart",
   "description": "Number of peers subscribed to each topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"count\", \"instance_name\" FROM \"topic_peers_counts\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "topic_subscription_status",
   "type": "table",
   "description": "Status of our subscription to this topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT \"instance_name\" as \"name\", \"instance_peer_id\" as \"peer_id\", \"hash\" as \"topic\", \"status\" FROM \"topic_subscription_status\"  WHERE \"run_id\" = '${run_id:text}'\n"
    }
   ]
  },
  { "title": "Metrics regarding mesh state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "mesh_peer_inclusion_events  (topic: ${topic})",
   "type": "table",
   "description": "Number of times we include peers in a topic mesh for different reasons.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT \"instance_name\" AS \"name\", \"instance_peer_id\" AS \"peer_id\", \"reason\",  \"count\" FROM \"mesh_peer_inclusion_events\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "mesh_peer_churn_events  (topic: ${topic})",
   "type": "table",
   "description": "Number of times we remove peers in a topic mesh for different reasons.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "SELECT \"instance_name\" AS \"name\", \"instance_peer_id\" AS \"peer_id\", \"reason\", \"count\" FROM \"mesh_peer_churn_events\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "mesh_peer_counts (topic: ${topic})",
   "type": "barchart",
   "description": "Number of peers in our mesh.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"count\", \"instance_name\" FROM \"mesh_peer_counts\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "Metrics regarding messages sent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "topic_msg_sent_counts  (topic: ${topic})",
   "type": "barchart",
   "description": "Number of gossip messages sent to each topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"instance_name\", \"count\" FROM \"topic_msg_sent_counts\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "topic_msg_sent_bytes  (topic: ${topic})",
   "type": "barchart",
   "description": "Bytes from gossip messages sent to each topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"instance_name\", \"count\" FROM \"topic_msg_sent_bytes\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "topic_msg_published  (topic: ${topic})",
   "type": "barchart",
   "description": "Number of gossipsub messages published to each topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"instance_name\", \"count\" FROM \"topic_msg_published\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "Metrics regarding messages received",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "topic_msg_recv_counts  (topic: ${topic})",
   "type": "barchart",
   "description": "Number of gossipsub messages received on each topic (after filtering duplicates).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"instance_name\", \"count\" FROM \"topic_msg_recv_counts\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "topic_msg_recv_counts_unfiltered  (topic: ${topic})",
   "type": "barchart",
   "description": "Number of gossipsub messages received on each topic (without filtering duplicates).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"instance_name\", \"count\" FROM \"topic_msg_recv_counts_unfiltered\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  {
   "title": "topic_msg_recv_bytes  (topic: ${topic})",
   "type": "barchart",
   "description": "Bytes received from gossip messages for each topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"instance_name\", \"count\" FROM \"topic_msg_recv_bytes\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}'"
    }
   ]
  },
  { "title": "Metrics related to scoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "score_per_mesh histogram (topic: ${topic}, instance: ${instance_name})",
   "type": "barchart",
   "description": "Histogram of the scores for each mesh topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "query": "SELECT count AS \"mesh\", upper_bound FROM \"score_per_mesh\" WHERE \"run_id\" = '${run_id:text}' AND \"hash\" = '${topic:text}' AND \"instance_name\" = '${instance_name}'"
    }
   ]
  },
  {
   "title": "scoring_penalties",
   "type": "table",
   "description": "A counter of the kind of penalties being applied to peers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "query": "SELECT instance_name AS \"name\", instance_peer_id AS \"peer_id\", penalty, count FROM \"scoring_penalties\" WHERE \"run_id\" = '${run_id:text}' "
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "peers_per_protocol (protocol: ${protocol})",
   "type": "barchart",
   "description": "The number of peers that are connected to each protocol.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "repeat": "protocol",
   "targets": [
    {
     "query": "SELECT instance_name AS \"name\", peers FROM \"peers_per_protocol\" WHERE \"run_id\" = '${run_id:text}' AND protocol = '${protocol:text}'"
    }
   ]
  },
  {
   "title": "heartbeat_duration histogram (instance: ${instance_name})",
   "type": "barchart",
   "description": "The time it takes to complete one iteration of the heartbeat.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT upper_bound, count FROM \"heartbeat_duration\" WHERE run_id = '${run_id:text}' AND instance_name = '${instance_name:text}'"
    }
   ]
  },
  { "title": "Performance metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "memcache_misses",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT instance_name AS \"name\", count FROM \"memcache_misses\" WHERE \"run_id\" = '${run_id:text}' "
    }
   ]
  }
 ]
}