name = "gossipsub-testground"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "episub"
instances = { min = 2, max = 100, default = 2 }
