{
 "title": "Messages",
 "time": { "from": "2022-11-24T14:34:06.606Z", "to": "2022-11-24T15:05:06.894Z" },
 "templating": {
  "list": [
   { "name": "run_id", "query": "cdvo64r4lvk9splekvog" }
  ]
 },
 "panels": [
  { "title": "Beacon Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Beacon Blocks per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_beacon_block WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Aggregate and Proof Attestation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Aggregates_0 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_aggregates_0 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Aggregates_1 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_aggregates_1 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Aggregates_2 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_aggregates_2 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Aggregates_3 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_aggregates_3 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  { "title": "Attestation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Attestations_0 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_attestations_0 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Attestations_1 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_attestations_1 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Attestations_2 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_attestations_2 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "Attestations_3 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_attestations_3 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  { "title": "Signed Contribution and Proof", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "SignedContributionAndProof_0 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_0 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "SignedContributionAndProof_1 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_1 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "SignedContributionAndProof_2 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_2 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "SignedContributionAndProof_3 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_3 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  { "title": "Sync Committee Message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "SyncCommitteeMessage_0 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_0 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "SyncCommitteeMessage_1 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_1 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "SyncCommitteeMessage_2 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_2 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  },
  {
   "title": "SyncCommitteeMessage_3 per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "query": "SELECT MEAN(\"count\") AS mean, MIN(\"count\") AS min, MAX(\"count\") AS max FROM scoring_sync_committee_aggregates_3 WHERE run_id = '${run_id:text}' GROUP BY time(384s)"
    }
   ]
  }
 ]
}