{
 "title": "Peer Scores and Gossipsub Metrics",
 "time": { "from": "2022-11-16T23:42:12.567Z", "to": "2022-11-16T23:45:24.494Z" },
 "templating": {
  "list": [
   { "name": "run_id", "query": "cdqnac34lvk27aesepm0" },
   {
    "name": "peer_id",
    "query": "12D3KooWBxZrvCGaRQJbYXQVwMQ38C9JhxU8Pab7N7oEDTtkASYn"
   }
  ]
 },
 "panels": [
  { "title": "Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peer Scores ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT * FROM scoring_scores WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}'"
    }
   ]
  },
  {
   "title": "Peer Scores (attacker only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT * FROM scoring_scores WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}'"
    }
   ]
  },
  {
   "title": "Metrics regarding messages sent/received",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "topic_msg_sent_counts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Blocks",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '\\\\\"Blocks\\\\\"'"
    },
    {
     "alias": "Attestations_0",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":0}'"
    },
    {
     "alias": "Attestations_1",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":1}'"
    },
    {
     "alias": "Attestations_2",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":2}'"
    },
    {
     "alias": "Attestations_3",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":3}'"
    },
    {
     "alias": "Aggregates_0",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":0}'"
    },
    {
     "alias": "Aggregates_1",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":1}'"
    },
    {
     "alias": "Aggregates_2",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":2}'"
    },
    {
     "alias": "Aggregates_3",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":3}'"
    },
    {
     "alias": "SyncMessages_0",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":0}'"
    },
    {
     "alias": "SyncMessages_1",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":1}'"
    },
    {
     "alias": "SyncMessages_2",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":2}'"
    },
    {
     "alias": "SyncMessages_3",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":3}'"
    },
    {
     "alias": "SignedContributionAndProof_0",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":0}'"
    },
    {
     "alias": "SignedContributionAndProof_1",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":1}'"
    },
    {
     "alias": "SignedContributionAndProof_2",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":2}'"
    },
    {
     "alias": "SignedContributionAndProof_3",
     "query": "SELECT count from scoring_topic_msg_sent_counts WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":3}'"
    }
   ]
  },
  {
   "title": "topic_msg_sent_bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "Blocks",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '\\\\\"Blocks\\\\\"'"
    },
    {
     "alias": "Attestations_0",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":0}'"
    },
    {
     "alias": "Attestations_1",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":1}'"
    },
    {
     "alias": "Attestations_2",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":2}'"
    },
    {
     "alias": "Attestations_3",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":3}'"
    },
    {
     "alias": "Aggregates_0",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":0}'"
    },
    {
     "alias": "Aggregates_1",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":1}'"
    },
    {
     "alias": "Aggregates_2",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":2}'"
    },
    {
     "alias": "Aggregates_3",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":3}'"
    },
    {
     "alias": "SyncMessages_0",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":0}'"
    },
    {
     "alias": "SyncMessages_1",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":1}'"
    },
    {
     "alias": "SyncMessages_2",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":2}'"
    },
    {
     "alias": "SyncMessages_3",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":3}'"
    },
    {
     "alias": "SignedContributionAndProof_0",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":0}'"
    },
    {
     "alias": "SignedContributionAndProof_1",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":1}'"
    },
    {
     "alias": "SignedContributionAndProof_2",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":2}'"
    },
    {
     "alias": "SignedContributionAndProof_3",
     "query": "SELECT count from scoring_topic_msg_sent_bytes WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":3}'"
    }
   ]
  },
  {
   "title": "topic_msg_published",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "Blocks",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '\\\\\"Blocks\\\\\"'"
    },
    {
     "alias": "Attestations_0",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":0}'"
    },
    {
     "alias": "Attestations_1",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":1}'"
    },
    {
     "alias": "Attestations_2",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":2}'"
    },
    {
     "alias": "Attestations_3",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":3}'"
    },
    {
     "alias": "Aggregates_0",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":0}'"
    },
    {
     "alias": "Aggregates_1",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":1}'"
    },
    {
     "alias": "Aggregates_2",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":2}'"
    },
    {
     "alias": "Aggregates_3",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":3}'"
    },
    {
     "alias": "SyncMessages_0",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":0}'"
    },
    {
     "alias": "SyncMessages_1",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":1}'"
    },
    {
     "alias": "SyncMessages_2",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":2}'"
    },
    {
     "alias": "SyncMessages_3",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":3}'"
    },
    {
     "alias": "SignedContributionAndProof_0",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":0}'"
    },
    {
     "alias": "SignedContributionAndProof_1",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":1}'"
    },
    {
     "alias": "SignedContributionAndProof_2",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":2}'"
    },
    {
     "alias": "SignedContributionAndProof_3",
     "query": "SELECT count from scoring_topic_msg_published WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":3}'"
    }
   ]
  },
  {
   "title": "topic_msg_recv_counts_unfiltered",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "Blocks",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '\\\\\"Blocks\\\\\"'"
    },
    {
     "alias": "Attestations_0",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":0}'"
    },
    {
     "alias": "Attestations_1",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":1}'"
    },
    {
     "alias": "Attestations_2",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":2}'"
    },
    {
     "alias": "Attestations_3",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Attestations\\\\\":3}'"
    },
    {
     "alias": "Aggregates_0",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":0}'"
    },
    {
     "alias": "Aggregates_1",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":1}'"
    },
    {
     "alias": "Aggregates_2",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":2}'"
    },
    {
     "alias": "Aggregates_3",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"Aggregates\\\\\":3}'"
    },
    {
     "alias": "SyncMessages_0",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":0}'"
    },
    {
     "alias": "SyncMessages_1",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":1}'"
    },
    {
     "alias": "SyncMessages_2",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":2}'"
    },
    {
     "alias": "SyncMessages_3",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SyncMessages\\\\\":3}'"
    },
    {
     "alias": "SignedContributionAndProof_0",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":0}'"
    },
    {
     "alias": "SignedContributionAndProof_1",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":1}'"
    },
    {
     "alias": "SignedContributionAndProof_2",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":2}'"
    },
    {
     "alias": "SignedContributionAndProof_3",
     "query": "SELECT count from scoring_topic_msg_recv_counts_unfiltered WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":3}'"
    }
   ]
  },
  { "title": "Metrics regarding mesh state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "mesh_peer_churn_events (BadScore)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "alias": "Blocks",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '\\\\\"Blocks\\\\\"'"
    },
    {
     "alias": "Attestations_0",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Attestations\\\\\":0}'"
    },
    {
     "alias": "Attestations_1",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Attestations\\\\\":1}'"
    },
    {
     "alias": "Attestations_2",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Attestations\\\\\":2}'"
    },
    {
     "alias": "Attestations_3",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Attestations\\\\\":3}'"
    },
    {
     "alias": "Aggregates_0",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Aggregates\\\\\":0}'"
    },
    {
     "alias": "Aggregates_1",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Aggregates\\\\\":1}'"
    },
    {
     "alias": "Aggregates_2",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Aggregates\\\\\":2}'"
    },
    {
     "alias": "Aggregates_3",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"Aggregates\\\\\":3}'"
    },
    {
     "alias": "SyncMessages_0",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SyncMessages\\\\\":0}'"
    },
    {
     "alias": "SyncMessages_1",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SyncMessages\\\\\":1}'"
    },
    {
     "alias": "SyncMessages_2",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SyncMessages\\\\\":2}'"
    },
    {
     "alias": "SyncMessages_3",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SyncMessages\\\\\":3}'"
    },
    {
     "alias": "SignedContributionAndProof_0",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":0}'"
    },
    {
     "alias": "SignedContributionAndProof_1",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":1}'"
    },
    {
     "alias": "SignedContributionAndProof_2",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":2}'"
    },
    {
     "alias": "SignedContributionAndProof_3",
     "query": "SELECT count from scoring_mesh_peer_churn_events WHERE run_id = '${run_id:text}' AND peer_id = '${peer_id:text}' AND reason = 'BadScore' AND hash = '{\\\\\"SignedContributionAndProof\\\\\":3}'"
    }
   ]
  }
 ]
}