[metadata]
name = "eth_consensus"

[global]
  builder = "docker:generic"
  plan = "gossipsub-testground/eth_consensus"
  case = "eth_consensus"
  runner = "local:docker"

  [global.build_config]
    path = "./"

[[groups]]
  id = "main-instances"
  instances = { count = 3 }

  [groups.run]
  # Check the plan (./eth_consensus/manifest.toml) to understand the meaning of each param
  test_params = { seed = "40", no_val_percentage = "60", total_validators = "200", min_peers_per_node = "2", max_peers_per_node_inclusive = "3", run = "120" }

