[metadata]
name = "eth_consensus"

[global]
  builder = "docker:generic"
  plan = "gossipsub-testground/eth_consensus"
  case = "eth_consensus"
  runner = "local:docker"

  [global.build_config]
    path = "./"

[[groups]]
  id = "main-instances"
  instances = { count = 40 }

  [groups.run]
  # Check the plan (./eth_consensus/manifest.toml) to understand the meaning of each param
  test_params = { seed = "40", no_val_percentage = "60", total_validators = "20000", min_peers_per_node = "4", max_peers_per_node_inclusive = "10", run = "500", episub = "true" }

