[metadata]
name = "censoring"
author = "Akihito Nakano"

[global]
plan = "gossipsub-testground/scoring-parameters"
case = "scoring-parameters"
total_instances = 5
builder = "docker:generic"
runner = "local:docker"
disable_metrics = false

[[groups]]
id = "beacon_node"
  [groups.instances]
  count = 4
  [groups.run]
    [groups.run.test_params]

[[groups]]
id = "attacker"
  [groups.instances]
  count = 1
  [groups.run]
    [groups.run.test_params]
